######################################################################
# Automatically generated by qmake (2.01a) Mon May 21 13:53:59 2012
######################################################################

TEMPLATE = app
TARGET = miqrochat
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += miqrochat.cpp \
    MessageEdit.cpp \
    ChatHeader.cpp

HEADERS += \
    MessageEdit.h \
    ChatHeader.h
